#!/bin/bash
echo "========================================="
echo "  SaaSly - Stripe Test Mode Setup"
echo "========================================="
echo ""
echo "Follow these steps to enable Stripe payments:"
echo ""
echo "1. Go to https://dashboard.stripe.com/register"
echo "2. Create a free Stripe account"
echo "3. Go to https://dashboard.stripe.com/test/apikeys"
echo "4. Copy your 'Secret key' (starts with sk_test_)"
echo "5. Go to https://dashboard.stripe.com/webhooks"
echo "6. Click 'Add endpoint'"
echo "7. Set URL to: https://your-backend-url.onrender.com/api/stripe/webhook"
echo "8. Select events: checkout.session.completed, customer.subscription.updated, customer.subscription.deleted"
echo "9. Copy the 'Signing secret' (starts with whsec_)"
echo ""
echo "10. Update saas-dashboard/backend/.env with your keys:"
echo "    STRIPE_SECRET_KEY=sk_test_xxxxx"
echo "    STRIPE_WEBHOOK_SECRET=whsec_xxxxx"
echo ""
echo "11. Restart the backend server"
echo ""
echo "TEST CARD NUMBERS (Stripe Test Mode):"
echo "  Success:        4242 4242 4242 4242"
echo "  Requires auth:  4000 0025 0000 3155"
echo "  Declined:       4000 0000 0000 0002"
echo ""
echo "Use any future expiry (e.g. 12/34), any CVC, any ZIP."
echo "========================================="
